name: Restore Pnpm Store and Install Dependencies
description: Restore Pnpm Store and Install Dependencies

inputs:
  working-directory:
    description: "Working directory"
    required: false
    default: .

runs:
  using: "composite"
  steps:
    - name: Setup Node.js Environment
      uses: actions/setup-node@v4
      with:
        node-version-file: package.json
        registry-url: https://registry.npmjs.org

    - name: Setup Pnpm
      uses: pnpm/action-setup@v4
      with:
        package_json_file: package.json

    - name: Get Pnpm Store Directory
      id: pnpm-cache
      run: |
        cd ${{ inputs.working-directory }}
        echo "STORE_PATH=$(pnpm store path)" >> "$GITHUB_OUTPUT"
      shell: bash

    - name: Restore Pnpm Store
      uses: actions/cache@v4
      env:
        cache-name: pnpm-store-cache
      with:
        path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
        key: ${{ env.cache-name }}-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}

    - name: Install Dependencies
      run: |
        cd ${{ inputs.working-directory }}
        pnpm install --frozen-lockfile
      shell: bash