name: Install pnpm and pnpm install

runs:
  using: 'composite'
  steps:
    - name: Setup Node
      uses: actions/setup-node@v4
    - name: Setup pnpm
      uses: pnpm/action-setup@v3.0.0
      with:
        version: 'latest'
    - name: Setup Node.js environment
      uses: actions/setup-node@v4
      with:
        node-version: 'latest'
        cache: 'pnpm'
        cache-dependency-path: 'pnpm-lock.yaml'
    - name: Install dependencies
      run: pnpm install
    - name: Build
      run: pnpm run generate:docs
