name: Restore pnpm store and install dependencies

inputs:
  working-directory:
    descirption: "Working directory"
    default: .
    required: false
  package-json-file:
    type: string
    default: "package.json"
    required: false

runs:
  using: "composite"
  steps:
    - name: Setup Node.js environment
      uses: actions/setup-node@v4
      with:
        node-version-file: ${{ inputs.package-json-file }}

    - uses: pnpm/action-setup@v4
      with:
        package_json_file: ${{ inputs.package-json-file }}

    - name: Get pnpm store directory
      id: pnpm-cache
      run: |
        cd ${{ inputs.working-directory }}
        echo "STORE_PATH=$(pnpm store path)" >> "$GITHUB_OUTPUT"
      shell: bash

    - name: Restore pnpm store
      uses: actions/cache@v4
      env:
        cache-name: pnpm-store-cache
      with:
        path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
        key: ${{ env.cache-name }}-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}

    - name: Install dependencies
      run: |
        cd ${{ inputs.working-directory }}
        pnpm install --frozen-lockfile
      shell: bash