name: Github Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  setup:
    uses: zhumeisongsong/shared-actions/.github/workflows/reusable-pnpm-setup.yml@main

  release:
    needs: setup
    uses: zhumeisongsong/shared-actions/.github/workflows/reusable-semantic-release.yml@main
    secrets:
      REPO_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}