name: Pnpm Setup

on:
  workflow_call:

jobs:
  setup:
    name: Setup Pnpm
    timeout-minutes: 15
    defaults:
      run:
        working-directory: .
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: "package.json"

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        id: pnpm-install
        with:
          package_json_file: "package.json"
          run_install: false